In [1]:
import numpy as np

In [2]:
x = [1,2,3,4]
y = [2,3,4,6]

In [5]:
nx = np.array(x)
ny = np.array(y)

In [6]:
print(nx,ny)

[1 2 3 4] [2 3 4 6]


In [7]:
print(x,y)

[1, 2, 3, 4] [2, 3, 4, 6]


In [8]:
nx + ny

array([ 3,  5,  7, 10])

In [11]:
ny ** nx

array([   2,    9,   64, 1296])

In [12]:
nx.size

4

In [13]:
nx.shape

(4,)

In [14]:
nx.data

In [26]:
nz = np.array([12,32,44,2])

In [27]:
nz = np.array([12,32,44,2],dtype='float')

In [28]:
nz.dtype

dtype('float64')

In [29]:
type(nx)

numpy.ndarray

In [33]:
x1 = [1,2,3]
x2 = [3,3,4]
x3 = [4,1,2]
x = np.array([x1,x2,x3])

y1 = [5,4,1]
y2 = [2,1,2]
y3 = [1,3,6]
y = np.array([y1,y2,y3])

z = np.array([[13, 12, 13],[31, 13 ,41],[24 ,21 ,22]])


In [37]:
x.shape

(3, 3)

In [40]:
x.size

9

In [43]:
print(x)
print(y)

[[1 2 3]
 [3 3 4]
 [4 1 2]]
[[5 4 1]
 [2 1 2]
 [1 3 6]]


In [42]:
x.dot(y)

array([[12, 15, 23],
       [25, 27, 33],
       [24, 23, 18]])

In [44]:
x*y

array([[ 5,  8,  3],
       [ 6,  3,  8],
       [ 4,  3, 12]])

In [45]:
x.mean()

2.5555555555555554

In [46]:
x.std()

1.0657403385139377

In [47]:
x.max(),x.min()

(4, 1)

In [52]:
x[2]

array([4, 1, 2])

In [49]:
y[0]

array([5, 4, 1])

In [56]:
x.cumsum()

array([ 1,  3,  6,  9, 12, 16, 20, 21, 23])

In [57]:
x.diagonal()

array([1, 3, 2])

In [59]:
x.T

array([[1, 3, 4],
       [2, 3, 1],
       [3, 4, 2]])

In [60]:
x.transpose()

array([[1, 3, 4],
       [2, 3, 1],
       [3, 4, 2]])

In [62]:
x.reshape(1,9)

array([[1, 2, 3, 3, 3, 4, 4, 1, 2]])

In [65]:
x.resize(3,3)

In [66]:
x

array([[1, 2, 3],
       [3, 3, 4],
       [4, 1, 2]])

In [85]:
seq1 = np.arange(-np.pi,np.pi,0.05)

In [86]:
seq1

array([-3.14159265, -3.09159265, -3.04159265, -2.99159265, -2.94159265,
       -2.89159265, -2.84159265, -2.79159265, -2.74159265, -2.69159265,
       -2.64159265, -2.59159265, -2.54159265, -2.49159265, -2.44159265,
       -2.39159265, -2.34159265, -2.29159265, -2.24159265, -2.19159265,
       -2.14159265, -2.09159265, -2.04159265, -1.99159265, -1.94159265,
       -1.89159265, -1.84159265, -1.79159265, -1.74159265, -1.69159265,
       -1.64159265, -1.59159265, -1.54159265, -1.49159265, -1.44159265,
       -1.39159265, -1.34159265, -1.29159265, -1.24159265, -1.19159265,
       -1.14159265, -1.09159265, -1.04159265, -0.99159265, -0.94159265,
       -0.89159265, -0.84159265, -0.79159265, -0.74159265, -0.69159265,
       -0.64159265, -0.59159265, -0.54159265, -0.49159265, -0.44159265,
       -0.39159265, -0.34159265, -0.29159265, -0.24159265, -0.19159265,
       -0.14159265, -0.09159265, -0.04159265,  0.00840735,  0.05840735,
        0.10840735,  0.15840735,  0.20840735,  0.25840735,  0.30

In [93]:
seq2 = np.linspace(10,20,10)
seq2

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [98]:
np.zeros(shape=(10,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [99]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [105]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [107]:
np.random.rand(5)

array([0.34201356, 0.34189849, 0.26424874, 0.05504006, 0.1239466 ])

In [108]:
np.random.rand(4,3)

array([[0.65318404, 0.32520961, 0.48723959],
       [0.34310723, 0.66986103, 0.61429176],
       [0.05592519, 0.33635889, 0.05355029],
       [0.34688721, 0.61781202, 0.76697915]])

In [113]:
np.random.randint(1,11,(3,4))

array([[ 8,  6,  3,  6],
       [ 6,  3,  3,  1],
       [ 5, 10,  2, 10]])

In [117]:
x= [1,2,3,1,12,31,23,123]
np.random.shuffle(x)
x

[31, 3, 23, 12, 1, 123, 2, 1]

In [17]:
fives=np.random.randint(1,100,(15,15))

In [18]:
fives

array([[89,  4, 26, 24, 59, 57, 78, 83,  6, 45, 35, 93, 82, 48, 79],
       [85, 35, 98,  6, 18, 99, 90, 76, 84, 71, 56, 90, 21, 56, 17],
       [45, 85, 13, 83, 40,  8,  6, 60, 42, 93, 38, 96,  9,  2, 79],
       [38, 16, 65, 79, 61, 86, 29, 46, 16, 98, 58, 70, 23, 88, 11],
       [17, 29,  3, 20, 58, 92, 86, 70, 75,  8,  6, 76, 29, 79, 85],
       [51, 73,  9, 15, 94, 95, 21, 65, 15, 32, 33, 90, 23, 39, 75],
       [98,  4, 76, 86, 61, 25, 49, 10,  5,  5, 68,  6, 99, 19, 77],
       [88, 95, 84, 13, 99, 87, 15, 18, 61, 24, 27,  7, 83, 98, 13],
       [89, 94, 43, 59, 36, 10, 91, 26, 83,  7, 14, 89, 54, 99, 64],
       [85, 98, 57, 67, 71, 16, 14, 64, 50, 44, 12, 75,  1, 64, 37],
       [76, 39,  6, 98, 44, 67, 11, 59,  6, 89, 39, 74, 84, 60, 29],
       [52, 82, 94, 60, 79, 13, 93, 49, 97,  2, 40, 33, 37, 90, 27],
       [45, 84, 66, 97, 38, 21, 25, 14,  4,  7, 12,  5, 69, 81, 18],
       [11, 11, 26, 18, 94, 30, 18, 23, 73, 41,  1, 11, 13, 97, 75],
       [53, 75, 49, 29, 16, 75, 20

In [4]:
fives[0]

array([97, 42,  1, 45,  7])

In [5]:
fives[0][3]

45

In [12]:
fives[0:3,2:]

array([[ 1, 45,  7],
       [58,  4, 53],
       [17, 49, 61]])

In [21]:
fives[0:5:2,1:5:2]

array([[ 4, 24],
       [85, 83],
       [29, 20]])